export class Chatbox {
  constructor(apiService) {
    this.api = apiService;

    // DOM Elements
    this.chatHistory = document.getElementById("chat-history");
    this.inputElement = document.getElementById("chat-input");
    this.sendButton = document.getElementById("send-btn");
    this.clearButton = document.getElementById("clear-chat-btn");

    this.initEventListeners();
    this.loadHistory();
  }

  // Called by main.js once the PDF is uploaded
  enable() {
    this.inputElement.disabled = false;
    this.sendButton.disabled = false;
    this.inputElement.focus();
  }

  initEventListeners() {
    this.sendButton.addEventListener("click", () => this.sendMessage());
    this.inputElement.addEventListener("keypress", (e) => {
      if (e.key === "Enter") this.sendMessage();
    });
    this.clearButton.addEventListener("click", () => this.clearHistory());
  }

  async sendMessage() {
    const text = this.inputElement.value.trim();
    if (!text) return;

    // 1. Render User Message
    this.renderMessage(text, "user");
    this.inputElement.value = "";

    // 2. Disable input and show loading
    this.inputElement.disabled = true;
    this.renderMessage("Thinking...", "bot", true);

    try {
      // Get the currently active file we saved earlier
      const targetFile = window.currentActiveFile;

      // Send BOTH the text and the filename to the API!
      const response = await this.api.askQuestion(text, targetFile);

      // Remove the loading text
      this.removeLoadingMessage();

      // Print the ACTUAL answer generated by Gemini
      this.renderMessage(response.answer, "bot");

      // Re-enable the input box
      this.inputElement.disabled = false;
      this.inputElement.focus();
    } catch (error) {
      console.error(error);
      this.removeLoadingMessage();
      this.renderMessage(
        "Sorry, I encountered an error connecting to the server.",
        "bot",
      );
      this.inputElement.disabled = false;
    }
  }

  // 🚨 NEW FUNCTION: Save a single message to browser memory
  saveToHistory(text, sender) {
    let history = JSON.parse(localStorage.getItem("aiChatHistory")) || [];
    history.push({ text, sender });
    localStorage.setItem("aiChatHistory", JSON.stringify(history));
  }

  // 🚨 NEW FUNCTION: Load all messages when page refreshes
  loadHistory() {
    let history = JSON.parse(localStorage.getItem("aiChatHistory")) || [];
    history.forEach((msg) => {
      // Pass 'false' at the end so it doesn't re-save to local storage while loading!
      this.renderMessage(msg.text, msg.sender, false, false);
    });
  }

  clearHistory() {
    // 1. Grab the custom modal elements
    const modal = document.getElementById("custom-modal-overlay");
    const confirmBtn = document.getElementById("modal-confirm-btn");
    const cancelBtn = document.getElementById("modal-cancel-btn");

    // 2. Show the modal with a smooth animation
    modal.classList.add("show");

    // 3. If they click Confirm (Destroy data)
    confirmBtn.onclick = () => {
      localStorage.removeItem("aiChatHistory");
      localStorage.removeItem("activeFileName");
      window.location.reload();
    };

    // 4. If they click Cancel (Hide the modal)
    cancelBtn.onclick = () => {
      modal.classList.remove("show");
    };

    // 5. Bonus UX: If they click the blurred background, close it
    modal.onclick = (e) => {
      if (e.target === modal) {
        modal.classList.remove("show");
      }
    };
  }

  renderMessage(text, sender, isLoading = false, save = true) {
    const div = document.createElement("div");
    div.className = `message ${sender}`;
    if (isLoading) div.id = "loading-msg";

    // 1. Add Avatar Icons!
    const avatar = document.createElement("div");
    avatar.className = "avatar";
    avatar.innerHTML =
      sender === "user"
        ? '<i class="fa-solid fa-user"></i>'
        : '<i class="fa-solid fa-robot"></i>';
    div.appendChild(avatar);

    // 2. Add Message Content Container
    const contentContainer = document.createElement("div");
    contentContainer.className = "msg-content";

    // 3. Handle Text vs Modern Typing Indicator
    if (isLoading) {
      contentContainer.innerHTML = `
            <div class="typing-indicator">
                <div class="dot"></div>
                <div class="dot"></div>
                <div class="dot"></div>
            </div>
        `;
    } else {
      const textSpan = document.createElement("span");
      textSpan.innerText = text;
      contentContainer.appendChild(textSpan);
    }

    div.appendChild(contentContainer);

    // 4. ADD AUDIO BUTTON (Only for actual bot answers)
    if (sender === "bot" && !isLoading) {
      const audioBtn = document.createElement("button");
      audioBtn.className = "audio-btn";
      audioBtn.innerHTML = '<i class="fa-solid fa-volume-high"></i> Read Aloud';
      audioBtn.type = "button";
      audioBtn.onclick = async (e) => {
        e.preventDefault();
        if (window.currentAudioBtn === audioBtn) {
          // If it's playing, pause it
          if (window.currentAudio && !window.currentAudio.paused) {
            window.currentAudio.pause();
            audioBtn.innerHTML =
              '<i class="fa-solid fa-play"></i> Resume Audio';
            return;
          }
          // If it's paused, resume it
          else if (
            window.currentAudio &&
            window.currentAudio.paused &&
            window.currentAudio.currentTime > 0
          ) {
            window.currentAudio.play();
            audioBtn.innerHTML =
              '<i class="fa-solid fa-pause"></i> Pause Audio';
            return;
          }
        }

        // 2. IS THE USER CLICKING A DIFFERENT BUTTON?
        if (window.currentAudio) {
          // Stop the old audio completely
          window.currentAudio.pause();
          window.currentAudio.currentTime = 0;

          // Reset the OLD button's text back to default
          if (window.currentAudioBtn) {
            window.currentAudioBtn.innerHTML =
              '<i class="fa-solid fa-volume-high"></i> Read Aloud';
          }
        }

        // 3. START GENERATING AUDIO FOR THE NEW BUTTON
        // Tell the browser this is now the active button
        window.currentAudioBtn = audioBtn;
        audioBtn.innerHTML =
          '<i class="fa-solid fa-hourglass-half"></i> Generating...';

        try {
          // Fetch and play the new audio
          const response = await this.api.getAudioFromText(text);
          window.currentAudio = new Audio(
            `data:${response.mimeType};base64,${response.audioBase64}`,
          );
          window.currentAudio.play();

          // Set the new button to Pause
          audioBtn.innerHTML = '<i class="fa-solid fa-pause"></i> Pause Audio';

          // 4. RESET EVERYTHING WHEN FINISHED
          window.currentAudio.onended = () => {
            audioBtn.innerHTML =
              '<i class="fa-solid fa-volume-high"></i> Read Aloud';
            window.currentAudio = null;
            window.currentAudioBtn = null;
          };
        } catch (err) {
          console.error(err);
          audioBtn.innerHTML =
            '<i class="fa-solid fa-circle-xmark"></i> Audio Error';
          window.currentAudioBtn = null;
        }
      };

      contentContainer.appendChild(document.createElement("br")); // line break for neatness
      contentContainer.appendChild(audioBtn);
    }

    this.chatHistory.appendChild(div);
    this.chatHistory.scrollTop = this.chatHistory.scrollHeight;

    if (save && !isLoading) {
      this.saveToHistory(text, sender);
    }
  }
  removeLoadingMessage() {
    const loader = document.getElementById("loading-msg");
    if (loader) loader.remove();
  }
}