export class Chatbox {
  constructor(apiService) {
    this.api = apiService;

    // DOM Elements
    this.chatHistory = document.getElementById("chat-history");
    this.inputElement = document.getElementById("chat-input");
    this.sendButton = document.getElementById("send-btn");

    this.initEventListeners();
  }

  // Called by main.js once the PDF is uploaded
  enable() {
    this.inputElement.disabled = false;
    this.sendButton.disabled = false;
    this.inputElement.focus();
  }

  initEventListeners() {
    this.sendButton.addEventListener("click", () => this.sendMessage());
    this.inputElement.addEventListener("keypress", (e) => {
      if (e.key === "Enter") this.sendMessage();
    });
  }

  async sendMessage() {
    const text = this.inputElement.value.trim();
    if (!text) return;

    // 1. Render User Message
    this.renderMessage(text, "user");
    this.inputElement.value = "";

    // 2. Disable input and show loading
    this.inputElement.disabled = true;
    this.renderMessage("Thinking...", "bot", true);

    try {
      // THE FIX: Call the real backend Node.js server!
      const response = await this.api.askQuestion(text);

      // Remove the loading text
      this.removeLoadingMessage();

      // Print the ACTUAL answer generated by Gemini
      this.renderMessage(response.answer, "bot");

      // Re-enable the input box
      this.inputElement.disabled = false;
      this.inputElement.focus();
    } catch (error) {
      console.error(error);
      this.removeLoadingMessage();
      this.renderMessage(
        "Sorry, I encountered an error connecting to the server.",
        "bot",
      );
      this.inputElement.disabled = false;
    }
  }

  renderMessage(text, sender, isLoading = false) {
    const div = document.createElement("div");
    div.className = `message ${sender}`;
    if (isLoading) div.id = "loading-msg";
    div.innerText = text;

    this.chatHistory.appendChild(div);
    this.chatHistory.scrollTop = this.chatHistory.scrollHeight; // Auto-scroll to bottom
  }

  removeLoadingMessage() {
    const loader = document.getElementById("loading-msg");
    if (loader) loader.remove();
  }
}