export class Chatbox {
  constructor(apiService) {
    this.api = apiService;

    // DOM Elements
    this.chatHistory = document.getElementById("chat-history");
    this.inputElement = document.getElementById("chat-input");
    this.sendButton = document.getElementById("send-btn");

    this.initEventListeners();
  }

  // Called by main.js once the PDF is uploaded
  enable() {
    this.inputElement.disabled = false;
    this.sendButton.disabled = false;
    this.inputElement.focus();
  }

  initEventListeners() {
    this.sendButton.addEventListener("click", () => this.sendMessage());
    this.inputElement.addEventListener("keypress", (e) => {
      if (e.key === "Enter") this.sendMessage();
    });
  }

  async sendMessage() {
    const text = this.inputElement.value.trim();
    if (!text) return;

    // 1. Render User Message
    this.renderMessage(text, "user");
    this.inputElement.value = "";

    // 2. Disable input and show loading
    this.inputElement.disabled = true;
    this.renderMessage("Thinking...", "bot", true);

    try {
      // Get the currently active file we saved earlier
      const targetFile = window.currentActiveFile;

      // Send BOTH the text and the filename to the API!
      const response = await this.api.askQuestion(text, targetFile);

      // Remove the loading text
      this.removeLoadingMessage();

      // Print the ACTUAL answer generated by Gemini
      this.renderMessage(response.answer, "bot");

      // Re-enable the input box
      this.inputElement.disabled = false;
      this.inputElement.focus();
    } catch (error) {
      console.error(error);
      this.removeLoadingMessage();
      this.renderMessage(
        "Sorry, I encountered an error connecting to the server.",
        "bot",
      );
      this.inputElement.disabled = false;
    }
  }

  renderMessage(text, sender, isLoading = false) {
    const div = document.createElement("div");
    div.className = `message ${sender}`;
    if (isLoading) div.id = "loading-msg";

    // 1. Put the message text in its own span
    const textSpan = document.createElement("span");
    textSpan.innerText = text;
    div.appendChild(textSpan);

    // 2. 🚨 ADD AUDIO BUTTON (Only for actual bot answers)
    if (sender === "bot" && !isLoading) {
      const audioBtn = document.createElement("button");
      audioBtn.className = "audio-btn";
      audioBtn.innerHTML = "🔊 Read Aloud";

     audioBtn.onclick = async () => {
       // 1. If it's already playing, pause it easily!
       if (window.currentAudio && !window.currentAudio.paused) {
         window.currentAudio.pause();
         audioBtn.innerHTML = "▶️ Resume Audio";
         return;
       } else if (
         window.currentAudio &&
         window.currentAudio.paused &&
         window.currentAudio.currentTime > 0
       ) {
         // If it was paused, resume it!
         window.currentAudio.play();
         audioBtn.innerHTML = "⏸️ Pause Audio";
         return;
       }

       audioBtn.innerHTML = "⏳ Generating...";

       try {
         // 2. Fetch the WAV Base64 from your server
         const response = await this.api.getAudioFromText(text);

         // 3. Create a standard HTML Audio player (No atob() needed!)
         window.currentAudio = new Audio(
           `data:${response.mimeType};base64,${response.audioBase64}`,
         );

         // 4. Play it!
         window.currentAudio.play();
         audioBtn.innerHTML = "⏸️ Pause Audio";

         // 5. Reset button when finished
         window.currentAudio.onended = () => {
           audioBtn.innerHTML = "🔊 Read Aloud";
           window.currentAudio = null;
         };
       } catch (err) {
         console.error(err);
         audioBtn.innerHTML = "❌ Audio Error";
       }
     };

      div.appendChild(audioBtn);
    }

    this.chatHistory.appendChild(div);
    this.chatHistory.scrollTop = this.chatHistory.scrollHeight; // Auto-scroll to bottom
  }

  removeLoadingMessage() {
    const loader = document.getElementById("loading-msg");
    if (loader) loader.remove();
  }
}